-- MySQL Script generated by MySQL Workbench
-- Wed May 25 13:52:31 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema Location_de_film
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Location_de_film
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Location_de_film` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `Location_de_film` ;

-- -----------------------------------------------------
-- Table `Location_de_film`.`Film`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Location_de_film`.`Film` (
  `Titre` VARCHAR(45) NOT NULL,
  `Date_de_Sortie` DATETIME NOT NULL,
  `Durée` TIME NOT NULL,
  `Réalisateur` VARCHAR(45) NOT NULL,
  `Clients_idInfos_clients` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`Clients_idInfos_clients`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Location_de_film`.`Catégorie _de_film`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Location_de_film`.`Catégorie _de_film` (
  `Action` VARCHAR(45) NOT NULL,
  `Comédie` VARCHAR(45) NOT NULL,
  `Aventure` VARCHAR(45) NOT NULL,
  `Drame` VARCHAR(45) NOT NULL,
  `Horreur` VARCHAR(45) NOT NULL,
  `Film_Clients_idInfos_clients` INT NOT NULL,
  `Catégorie _de_filmcol` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Film_Clients_idInfos_clients`, `Catégorie _de_filmcol`),
  CONSTRAINT `fk_Catégorie _de_film_Film1`
    FOREIGN KEY (`Film_Clients_idInfos_clients`)
    REFERENCES `Location_de_film`.`Film` (`Clients_idInfos_clients`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `Location_de_film`.`Historique_modification`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Location_de_film`.`Historique_modification` (
  `Derniere date de modification` DATETIME NOT NULL,
  `Clients_idInfos_clients` INT NOT NULL,
  PRIMARY KEY (`Clients_idInfos_clients`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Location_de_film`.`Clients`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Location_de_film`.`Clients` (
  `idInfos_clients` INT NOT NULL AUTO_INCREMENT,
  `Nom` VARCHAR(45) NOT NULL,
  `Prénoms` VARCHAR(45) NOT NULL,
  `Email` VARCHAR(45) NOT NULL,
  `Historique_modification_Clients_idInfos_clients` INT NOT NULL,
  PRIMARY KEY (`idInfos_clients`, `Historique_modification_Clients_idInfos_clients`),
  INDEX `fk_Clients_Historique_modification1_idx` (`Historique_modification_Clients_idInfos_clients` ASC) ,
  CONSTRAINT `fk_Clients_Historique_modification1`
    FOREIGN KEY (`Historique_modification_Clients_idInfos_clients`)
    REFERENCES `Location_de_film`.`Historique_modification` (`Clients_idInfos_clients`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Location_de_film`.`Payment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Location_de_film`.`Payment` (
  `idPayement` INT NOT NULL AUTO_INCREMENT,
  `Date_de_payment` DATETIME NOT NULL,
  `Description` VARCHAR(45) NOT NULL,
  `Montant` FLOAT NOT NULL,
  PRIMARY KEY (`idPayement`),
  INDEX  (`index2`) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Location_de_film`.`Louer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Location_de_film`.`Louer` (
  `Clients_idInfos_clients` INT NULL,
  `Film_Clients_idInfos_clients` INT NOT NULL,
  `Date de location` DATETIME NOT NULL,
  `Payment_idPayement` INT NOT NULL,
  PRIMARY KEY (`Clients_idInfos_clients`, `Film_Clients_idInfos_clients`, `Payment_idPayement`),
  INDEX `fk_Clients_has_Film_Film1_idx` (`Film_Clients_idInfos_clients` ASC) ,
  INDEX `fk_Louer_Payment1_idx` (`Payment_idPayement` ASC) ,
  CONSTRAINT `fk_Clients_has_Film_Clients1`
    FOREIGN KEY (`Clients_idInfos_clients`)
    REFERENCES `Location_de_film`.`Clients` (`idInfos_clients`)
    ON DELETE SET NULL
    ON UPDATE SET NULL,
  CONSTRAINT `fk_Clients_has_Film_Film1`
    FOREIGN KEY (`Film_Clients_idInfos_clients`)
    REFERENCES `Location_de_film`.`Film` (`Clients_idInfos_clients`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Louer_Payment1`
    FOREIGN KEY (`Payment_idPayement`)
    REFERENCES `Location_de_film`.`Payment` (`idPayement`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
